name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2

    - name: Install Ansible
      uses: BSFishy/pip-action@v1
      with:
        packages: ansible  

    - name: Setup `ansible.cfg` to pickup roles path
      run: "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

    - name: Add Ansible Hosts file
      run: |
        sudo mkdir -p /etc/ansible
        sudo touch /etc/ansible/hosts
        echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null

    - name: Install Ansible Dependencies (Roles)
      run: ansible-galaxy install -r requirements.yml

    - name: Check Ansible Playbook Syntax
      run: ansible-playbook main.yml --syntax-check

    - name: Copy test config.yml into place
      run: cp tests/config.yml config.yml

    - name: Test the playbook
      run: ansible-playbook --extra-vars '{\"configure_sudoers\":\"true\"}' main.yml

    - name: Test playbook idempotence
      run: |
        idempotence=$(mktemp)
        ansible-playbook --extra-vars '{\"configure_sudoers\":\"true\"}' main.yml | tee -a ${idempotence}
        tail ${idempotence} | grep -q 'changed=0.*failed=0'  && \
         (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
